name: crm
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
#  sdk: '>=2.12.0-0 <3.0.0'location:

dependencies:

#  countly_flutter:
#    git:
#      url: https://github.com/Countly/countly-sdk-flutter-bridge.git
#      ref: master

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0

  dio: ^4.0.0
  bot_toast: ^4.0.1
  shared_preferences: ^2.0.6
  #路由
  fluro: ^2.0.3
  #  thrio: ^1.7.6

  #    微信支付以及登录
  # fluwx: ^2.6.2
  #UI
  pull_to_refresh: ^2.0.0
  #  lazy_load_refresh_indicator:
  #  tab_indicator_styler: ^1.0.0
  azlistview: ^1.1.1
  lpinyin: ^2.0.3
  #日期
#  flutter_date_pickers: ^0.2.4
  #控件库
  #  getwidget: ^1.2.4
  #getwidget: ^2.0.0-nullsafety.3
  photo_view: ^0.11.1
  #  柱状图
  charts_flutter: ^0.10.0
  #  动画
  #  animate_do: ^2.0.0

  #生命周期监听
  lifecycle: ^0.2.0
  #轮播
  #  flutter_swiper:
  #图片缓存
  cached_network_image: ^3.0.0

  #  paulonia_cache_image:

  #插件
  #  device_info: ^2.0.0
  package_info: ^2.0.2
  #  open_settings: ^1.0.3
  #  权限
  permission_handler: ^8.1.2

  #适配
  flutter_screenutil: ^5.0.0+2
  mime_type: ^1.0.0
  #  图片选择器
#  file_picker: ^3.0.0
  image_picker: ^0.8.1+2

  common_utils: ^2.0.2
  url_launcher: ^6.0.7
  #  缓存本地
  #sqflite_common_ffi: ^2.0.0
  #    级联选择器
  #  cascade_picker: ^0.0.4+1

  #  webview_flutter: ^2.0.2
  #  web_browser:

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  # flutter_smart_dialog: ^2.0.1
  flutter_picker: ^2.0.1
  universal_html: ^2.0.8

  #  flutter_widget_from_html_core: ^0.5.1+4

  #  rxdart:
  #  event_bus:

  #  fluttertoast: ^8.0.1-nullsafety.0
  #fluttertoast: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

analyzer:
  enable-experiment:
    - extension-methods
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images_shl/
    - assets/common/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  module:
    androidX: true
    androidPackage: com.zhongcai.crm
    iosBundleIdentifier: com.zhongcai.crm