name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: buildSdk
        run: ./gradlew buildSdk
      - name: lintSdk
        run: ./gradlew lintSdk
      - name: build sample/source
        run: ./gradlew build
      - name: unit test
        run: ./gradlew jvmTestSdk -S
      - name: run androidTestSdk on API 28 emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: default
          arch: x86_64
          profile: pixel_xl
          script: ./gradlew androidTestSdk

